# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
        server-id: ${{ vars.ARTIFACTORY_SERVER_ID }}
        server-username: ARTIFACTORY_USERNAME
        server-password: ARTIFACTORY_PASSWORD
        cache: maven

    - name: Setup SSH
      # You may pin to the exact commit or the version.
      # uses: prx0/setup-ssh-config@20710468a2f4df28f8b6d885f2b9cf34b3d0ccb7
      uses: prx0/setup-ssh-config@v1
      with:
        # ssh private key to contact the server with the public key
        private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        # host for the ssh config file
        host: github.com
        # hostname for the ssh config file
        hostname: github.com
        # user for the ssh config file
        user: git
        
    - name: Build with Maven
      run: |
       git config --global user.email "git@github.com"
       git config --global user.name "GitHub CI"
       git checkout -B main
       git tag --delete $(git tag)
       git fetch --all
       ./mvnw --batch-mode --no-transfer-progress clean release:prepare release:perform --file pom.xml
      env:
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASS_PHRASE }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
